server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/**  # 商品微服务的映射路径
  ignored-patterns: /upload/**
  ignored-services:
  - upload-service # 忽略upload-service服务
