server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://39.105.97.53:3306/heima?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: 39.105.97.53    #rabbitMQ虚拟机的ip，这里不需要配置端口，默认使用5672端口
    template:
      exchange: ALI.ITEM.EXCHANGE   #配置交换机，这样就不用在使用时再声名了
    publisher-confirms: true  #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.ali.item.pojo #实体类扫描位置